name: pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipython=9.0.0
  - pip
  - psutil
  - pip:
    - astropy==7.0.0
    - cupy-cuda12x==13.4.0
    - ipykernel==6.19.2
    - matplotlib==3.10.0
    - numba==0.57.0
    - numpy==1.24.4
    - python-dotenv==1.0.1
    - pyyaml==6.0.2
    - tqdm==4.67.1
    - watchdog==6.0.0
    - requests==2.31.0
    - pynvml
    - multiprocess
    - scipy
    - psycopg[binary]==3.2.12     
    - psycopg-pool==3.2.7         
    - pandas==2.3.3        