name: pipeline
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - ipython=9.0.0
  - numpy=1.24.4
  - scipy
  - pandas=2.3.3
  - matplotlib=3.10.0
  - astropy=7.0.0
  - numba=0.57.0
  - spherical-geometry
  - psutil
  - tqdm
  - watchdog
  - requests
  - pyyaml
  - python-dotenv

  # pip-only packages
  - pip
  - pip:
      - cupy-cuda12x==13.4.0
      - ipykernel==6.19.2
      - psycopg[binary]==3.2.12
      - psycopg-pool==3.2.7
      - pynvml
      - multiprocess